
    // Mapeamento completo dos SVGs
    const svgTextMap = {
        'Text Boldface.svg': '\\textbf{Text Boldface}',
        'Text Italics.svg': '\\textit{Text Italics}',
        'Text Roman.svg': '\\textrm{Text Roman}',
        'Text Sans-Serif.svg': '\\textsf{Text Sans-Serifs}',
        'Text Typewriter.svg': '\\texttt{Text Typewriter}',
        'Text Upwright.svg': '\\textup{Upwright}',
        'Blackboard Bold.svg': '\\mathbb{Blackboard\\; Bold}',
        'Bold Face.svg': '\\mathbf{Boldface}',
        'Boldface Italics.svg': '\\pmb{Boldfaced\\,Italics}',
        'Calligraphic.svg': '\\mathcal{Calligraphic}',
        'Fraktur.svg': '\\mathfrak{Fraktur}',
        'Italics.svg': '\\mathit{Italics}',
        'Roman.svg': '\\mathrm{Roman}',
        'Sans-Serif.svg': '\\mathsf{Sans-Serifs}',
        'Script.svg': '\\mathscr{Script}',
        'Typewriter.svg': '\\mathtt{Typewriter}',
        //spaces
        'equacao_1__square_____square.svg': '\\,',
        'equacao_2__square_____square.svg': '\\:',
        'equacao_3__square_____square.svg': '\\;',
        'equacao_4__square_____square.svg': '\\!',
        //symb7
        'equacao_1__widetilde_ijk_.svg': '\\widetilde{ijk}',
        'equacao_2__widehat_ijk_.svg': '\\widehat{ijk}',
        'equacao_3__overbrace_ijk_.svg': '\\overbrace{ijk}',
        'equacao_4__overbrace_ijk___a_.svg': '\\overbrace{ijk}^{a}',
        'equacao_5__underbrace_ijk_.svg': '\\underbrace{ijk}',
        'equacao_6__underbrace_ijk___a_.svg': '\\underbrace{ijk}_{a}',
        'equacao_7__overrightarrow_ijk_.svg': '\\overrightarrow{ijk}',
        'equacao_8__overset_a__ijk_.svg': '\\overset{a}{ijk}',
        'equacao_9__overleftarrow_ijk_.svg': '\\overleftarrow{ijk}',
        'equacao_10__underset_a__ijk_.svg': '\\underset{a}{ijk}',
        'equacao_11__overline_ijk_.svg': '\\overline{ijk}',
        'equacao_12__underline_ijk_.svg': '\\underline{ijk}',
        //equacao
        'equacao_1_x__a_.svg': 'x^{a}',
        'equacao_2__frac_a__b_.svg': '\\frac{a}{b}',
        'equacao_3__bigcap.svg': '\\bigcap',
        'equacao_4__sum.svg': '\\sum',
        'equacao_5__prod.svg': '\\prod',
        'equacao_6_x__a_.svg': 'x_{a}',
        'equacao_7_x_tfrac_x__a_.svg': 'x\\tfrac{x}{a}',
        'equacao_8__int__a___b_.svg': '\\int_{a}^{b}',
        'equacao_9__bigcap__a___b_.svg': '\\bigcap_{a}^{b}',
        'equacao_10__sum__a___b_.svg': '\\sum_{a}^{b}',
        'equacao_11__prod__a___v_.svg': '\\prod_{a}^{v}',
        'equacao_12_x__b___a_.svg': 'x_{b}^{a}',
        'equacao_13__frac__partial____partial_x_.svg': '\\frac{\\partial }{\\partial x}',
        'equacao_14__oint.svg': '\\oint',
        'equacao_15__bigcup.svg': '\\bigcup',
        'equacao_16__sqrt_x_.svg': '\\sqrt{x}',
        'equacao_17__coprod.svg': '\\coprod',
        'equacao_18__x__a____b_.svg': '{x_{a}}^{b}',
        'equacao_19__frac__partial_2____partial_x_2_.svg': '\\frac{\\partial^2 }{\\partial x^2}',
        'equacao_20__oint__a___b_.svg': '\\oint_{a}^{b}',
        'equacao_21__bigcup__a___b_.svg': '\\bigcup_{a}^{b}',
        'equacao_22__sqrt_n__x_.svg': '\\sqrt[n]{x}',
        'equacao_23__coprod__a___b_.svg': '\\coprod_{a}^{b}',
        'equacao_24___a___b__textrm_C_.svg': '_{a}^{b}\\textrm{C}',
        'equacao_25__frac__mathrm_d_____mathrm_d__x_.svg': '\\frac{\\mathrm{d} }{\\mathrm{d} x}',
        'equacao_26__iint__a___b_.svg': '\\iint_{a}^{b}',
        'equacao_27__displaystyle__lim__x__to_0_.svg': '\\displaystyle \\lim_{x \\to 0}',
        //greek
        'equacao_1__alpha.svg': '\\alpha',
        'equacao_2__beta.svg': '\\beta',
        'equacao_3__zeta.svg': '\\zeta',
        'equacao_4__kappa.svg': '\\kappa',
        'equacao_5__epsilon.svg': '\\epsilon',
        'equacao_6__varepsilon.svg': '\\varepsilon',
        'equacao_7__iota.svg': '\\iota',
        'equacao_8__xi.svg': '\\xi',
        'equacao_9__vartheta.svg': '\\vartheta',
        'equacao_10__theta.svg': '\\theta',
        'equacao_11__nu.svg': '\\nu',
        'equacao_12__lambda.svg': '\\lambda',
        'equacao_13__mu.svg': '\\mu',
        'equacao_14__rho.svg': '\\rho',
        'equacao_15__upsilon.svg': '\\upsilon',
        'equacao_16__varrho.svg': '\\varrho',
        'equacao_17__pi.svg': '\\pi',
        'equacao_18__varpi.svg': '\\varpi',
        'equacao_19__tau.svg': '\\tau',
        'equacao_20__psi.svg': '\\psi',
        'equacao_21__sigma.svg': '\\sigma',
        'equacao_22__varsigma.svg': '\\varsigma',
        'equacao_23__chi.svg': '\\chi',
        'equacao_24__phi.svg': '\\phi',
        'equacao_25__varphi.svg': '\\varphi',
        'equacao_26__delta.svg': '\\delta',
        'equacao_27__omega.svg': '\\omega',
        'equacao_28__gamma.svg': '\\gamma',
        //symb10
        'equacao_1__Phi.svg': '\\Phi',
        'equacao_2__Psi.svg': '\\Psi',
        'equacao_3__Omega.svg': '\\Omega',
        'equacao_4__Delta.svg': '\\Delta',
        'equacao_5__Theta.svg': '\\Theta',
        'equacao_6__Lambda.svg': '\\Lambda',
        'equacao_7__Xi.svg': '\\Xi',
        'equacao_8__Pi.svg': '\\Pi',
        'equacao_9__Sigma.svg': '\\Sigma',
        'equacao_10__Upsilon.svg': '\\Upsilon',
        'equacao_11__Gamma.svg': '\\Gamma',
        //symb6
        'equacao_1__bar_x_.svg': '\\bar{x}',
        'equacao_2__vec_x_.svg': '\\vec{x}',
        'equacao_3__dot_x_.svg': '\\dot{x}',
        'equacao_4__ddot_x_.svg': '\\ddot{x}',
        'equacao_5__hat_x_.svg': '\\hat{x}',
        'equacao_6__check_x_.svg': '\\check{x}',
        'equacao_7_x___.svg': "x{'}",
        'equacao_8_x_____.svg': "x^{''}",
        'equacao_9__tilde_x_.svg': '\\tilde{x}',
        'equacao_10__breve_x_.svg': '\\breve{x}',
        'equacao_11__not_x.svg': '\\not x',
        'equacao_12_x___circ_.svg': "x^{\\circ}",
        'equacao_13__grave_x_.svg': '\\grave{x}',
        'equacao_14__acute_x_.svg': '\\acute{x}',
        //symb5
        'equacao_1__subset.svg': '\\subset',
        'equacao_2__supset.svg': '\\supset',
        'equacao_3__subseteq.svg': '\\subseteq',
        'equacao_4__supseteq.svg': '\\supseteq',
        'equacao_5__nsubseteq.svg': '\\nsubseteq',
        'equacao_6__nsupseteq.svg': '\\nsupseteq',
        'equacao_7__subseteqq.svg': '\\subseteqq',
        'equacao_8__supseteqq.svg': '\\supseteqq',
        'equacao_9__nsubseteq.svg': '\\nsubseteq',
        'equacao_10__nsupseteqq.svg': '\\nsupseteqq',
        'equacao_11__sqsubset.svg': '\\sqsubset',
        'equacao_12__sqsupset.svg': '\\sqsupset',
        'equacao_13__sqsubseteq.svg': '\\sqsubseteq',
        'equacao_14__sqsupseteq.svg': '\\sqsupseteq',
        'equacao_15__in.svg': '\\in',
        'equacao_16__ni.svg': '\\ni',
        'equacao_17__notin.svg': '\\notin',
        //symb11
       'equacao_1__lt.svg': '\\lt',
        'equacao_2__gt.svg': '\\gt',
        'equacao_3__leq.svg': '\\leq',
        'equacao_4__geq.svg': '\\geq',
        'equacao_5__leqslant.svg': '\\leqslant',
        'equacao_6__geqslant.svg': '\\geqslant',
        'equacao_7__nless.svg': '\\nless',
        'equacao_8__ngtr.svg': '\\ngtr',
        'equacao_9__nleqslant.svg': '\\nleqslant',
        'equacao_10__ngeqslant.svg': '\\ngeqslant',
        'equacao_11__.svg': '=',
        'equacao_12__doteq.svg': '\\doteq',
        'equacao_13__neq.svg': '\\neq',
        'equacao_14__overset__underset__mathrm_def________.svg': '\\overset{\\underset{\\mathrm{def}}{}}{=}',
        'equacao_15__equiv.svg': '\\equiv',
        'equacao_16__not_equiv.svg': '\\not\\equiv',
        'equacao_17__sim.svg': '\\sim',
        'equacao_18__simeq.svg': '\\simeq',
        'equacao_19__approx.svg': '\\approx',
        'equacao_20__cong.svg': '\\cong',
        'equacao_21__prec.svg': '\\prec',
        'equacao_22__succ.svg': '\\succ',
        'equacao_23__preceq.svg': '\\preceq',
        'equacao_24__succeq.svg': '\\succeq',
        'equacao_25__ll.svg': '\\ll',
        'equacao_26__gg.svg': '\\gg',
        'equacao_27__vdash.svg': '\\vdash',
        'equacao_28__dashv.svg': '\\dashv',
        'equacao_29__smile.svg': '\\smile',
        'equacao_30__frown.svg': '\\frown',
        'equacao_31__models.svg': '\\models',
        'equacao_32__perp.svg': '\\perp',
        'equacao_33__asymp.svg': '\\asymp',
        'equacao_34__parallel.svg': '\\parallel',
        'equacao_35__mid.svg': '\\mid',
        'equacao_36__propto.svg': '\\propto',
        'equacao_37__bowtie.svg': '\\bowtie',
        'equacao_38__Join.svg': '\\Join',
        //symb2
        'equacao_1__pm.svg': '\\pm',
        'equacao_2__mp.svg': '\\mp',
        'equacao_3__dotplus.svg': '\\dotplus',
        'equacao_4__Cap.svg': '\\Cap',
        'equacao_5__Cup.svg': '\\Cup',
        'equacao_6__uplus.svg': '\\uplus',
        'equacao_7__times.svg': '\\times',
        'equacao_8__ast.svg': '\\ast',
        'equacao_9__div.svg': '\\div',
        'equacao_10__sqcap.svg': '\\sqcap',
        'equacao_11__sqcup.svg': '\\sqcup',
        'equacao_12__bigsqcup.svg': '\\bigsqcup',
        'equacao_13__wedge.svg': '\\wedge',
        'equacao_14__barwedge.svg': '\\barwedge',
        'equacao_15__cap.svg': '\\cap',
        'equacao_16__vee.svg': '\\vee',
        'equacao_17__veebar.svg': '\\veebar',
        'equacao_18__cup.svg': '\\cup',
        'equacao_19__triangleleft.svg': '\\triangleleft',
        'equacao_20__triangleright.svg': '\\triangleright',
        'equacao_21__bigtriangleup.svg': '\\bigtriangleup',
        'equacao_22__bigstar.svg': '\\bigstar',
        'equacao_23__star.svg': '\\star',
        'equacao_24__bigtriangledown.svg': '\\bigtriangledown',
        'equacao_25__dagger.svg': '\\dagger',
        'equacao_26__square.svg': '\\square',
        'equacao_27__blacksquare.svg': '\\blacksquare',
        'equacao_28__ddagger.svg': '\\ddagger',
        'equacao_29__triangle.svg': '\\triangle',
        'equacao_30__blacktriangle.svg': '\\blacktriangle',
        'equacao_31__wr.svg': '\\wr',
        'equacao_32__triangledown.svg': '\\triangledown',
        'equacao_33__blacktriangledown.svg': '\\blacktriangledown',
        'equacao_34__diamond.svg': '\\diamond',
        'equacao_35__lozenge.svg': '\\lozenge',
        'equacao_36__blacklozenge.svg': '\\blacklozenge',
        'equacao_37__bigcirc.svg': '\\bigcirc',
        'equacao_38__circ.svg': '\\circ',
        'equacao_39__bullet.svg': '\\bullet',
        'equacao_40__oslash.svg': '\\oslash',
        'equacao_41__circledcirc.svg': '\\circledcirc',
        'equacao_42__circleddash.svg': '\\circleddash',
        'equacao_43__bigodot.svg': '\\bigodot',
        'equacao_44__odot.svg': '\\odot',
        'equacao_45__cdot.svg': '\\cdot',
        'equacao_46__bigoplus.svg': '\\bigoplus',
        'equacao_47__oplus.svg': '\\oplus',
        'equacao_48__ominus.svg': '\\ominus',
        'equacao_49__bigotimes.svg': '\\bigotimes',
        'equacao_50__otimes.svg': '\\otimes',
        'equacao_51__circledast.svg': '\\circledast',
        'equacao_52__setminus.svg': '\\setminus',
        'equacao_53__amalg.svg': '\\amalg',
		'equacao_54__nabla.svg': '\\nabla',
        //symb8
        'equacao_1__leftarrow.svg': '\\leftarrow',
        'equacao_2__rightarrow.svg': '\\rightarrow',
        'equacao_3__Leftarrow.svg': '\\Leftarrow',
        'equacao_4__Rightarrow.svg': '\\Rightarrow',
        'equacao_5__leftrightarrow.svg': '\\leftrightarrow',
        'equacao_6__Leftrightarrow.svg': '\\Leftrightarrow',
        'equacao_7__mapsto.svg': '\\mapsto',
        'equacao_8__to.svg': '\\to',
        'equacao_9__leftharpoonup.svg': '\\leftharpoonup',
        'equacao_10__rightharpoonup.svg': '\\rightharpoonup',
        'equacao_11__leftrightharpoons.svg': '\\leftrightharpoons',
        'equacao_12__rightleftharpoons.svg': '\\rightleftharpoons',
        'equacao_13__xleftarrow_ijk__abc_.svg': '\\xleftarrow[ijk]{abc}',
        'equacao_14__xrightarrow_ijk__abc_.svg': '\\xrightarrow[ijk]{abc}',
        'equacao_15__overset_x___leftarrow_.svg': '\\overset{x}{\\leftarrow}',
        'equacao_16__overset_x___rightarrow_.svg': '\\overset{x}{\\rightarrow}',
        'equacao_17__underset_x___leftarrow_.svg': '\\underset{x}{\\leftarrow}',
        'equacao_18__underset_x___rightarrow_.svg': '\\underset{x}{\\rightarrow}',
        'equacao_19__uparrow.svg': '\\uparrow',
        //symb3
        'equacao_1__therefore.svg': '\\therefore',
        'equacao_2__partial.svg': '\\partial',
        'equacao_3__imath.svg': '\\imath',
        'equacao_4__because.svg': '\\because',
        'equacao_5__varnothing.svg': '\\varnothing',
        'equacao_6__jmath.svg': '\\jmath',
        'equacao_7__cdots.svg': '\\cdots',
        'equacao_8__infty.svg': '\\infty',
        'equacao_9__vdots.svg': '\\vdots',
        'equacao_10__ddots.svg': '\\ddots',
        'equacao_11__S.svg': '\\S',
        'equacao_12__wp.svg': '\\wp',
        'equacao_13__exists.svg': '\\exists',
        'equacao_14__forall.svg': '\\forall',
        'equacao_15__top.svg': '\\top',
        'equacao_16__Re.svg': '\\Re',
        'equacao_17__Im.svg': '\\Im',
        'equacao_18__mho.svg': '\\mho',
        'equacao_19__mathbb_N_.svg': '\\mathbb{N}',
        'equacao_20__mathbb_Z_.svg': '\\mathbb{Z}',
        'equacao_21__mathbb_R_.svg': '\\mathbb{R}',
        'equacao_22__mathbb_C_.svg': '\\mathbb{C}',
        'equacao_23__mathbb_Q_.svg': '\\mathbb{Q}',
        'equacao_24__mathbb_P_.svg': '\\mathbb{P}',
        'equacao_25__angle.svg': '\\angle',
        'equacao_26__measuredangle.svg': '\\measuredangle',
        'equacao_27__sphericalangle.svg': '\\sphericalangle',
        'equacao_28__mathbb_I_.svg': '\\mathbb{I}',
        //symb9
        'equacao_1__left___right_.svg': '\\left( \\right)',
        'equacao_2__left____right__.svg': '\\left\\| \\right\\|',
        'equacao_3__left___right_.svg': '\\left[ \\right]',
        'equacao_4__left___right_.svg': '\\left< \\right>',
        'equacao_5__left____right__.svg': '\\left\\{ \\right\\}',
        'equacao_6__left__lfloor__right__rfloor.svg': '\\left\\lfloor \\right\\rfloor',
        'equacao_7__left____right__.svg': '\\left| \\right|',
        'equacao_8__left__lceil__right__rceil.svg': '\\left\\lceil \\right\\rceil',
        'equacao_9__left____right___.svg': '\\left\\{ \\right.',
        'equacao_10____left___right___.svg': '\\left. \\right\\}',
        //symb12
        'equacao_3__binom_a__b_.svg': '\\binom{a}{b}'
    };


  
    
    document.addEventListener('DOMContentLoaded', function() {
        const svgImages = document.querySelectorAll('img[src*=".svg"]');
        
        //console.log('Encontrados', svgImages.length, 'SVGs'); // Debug
        
        svgImages.forEach(function(svgImg) {
            const filename = svgImg.getAttribute('src').split('/').pop();
            const textToInsert = svgTextMap[filename];
            
            //console.log('Ficheiro:', filename, 'Texto:', textToInsert); // Debug
            
            if (textToInsert) {
                svgImg.addEventListener('click', function() {
                   // console.log('Clicado em:', filename); // Debug
                    
                    // Tenta várias formas de inserir o texto
                    if (window.insertTextIntoBox) {
                        //console.log('Usando insertTextIntoBox'); // Debug
                        insertTextIntoBox(textToInsert);
                    } else {
                        //console.log('insertTextIntoBox não encontrada, a tentar alternativas'); // Debug
                        
                        // Alternativa: Procura por textarea ou input
                        const textbox = document.querySelector('textarea') || document.querySelector('input[type="text"]');
                        if (textbox) {
                            textbox.value += textToInsert;
                            textbox.focus();
                            //console.log('Texto inserido diretamente na textbox'); // Debug
                        } else {
                            alert('Texto para inserir: ' + textToInsert); // Fallback para teste
                        }
                    }
                });
            }
        });
    });